### ISSUE TITLE
[Question] How do you change the available editor actions?

### ISSUE THREAD

**Issue by Sobient** [CroudTech/vue-quill#16] opened 2017-09-18 13:14 UTC
Tried a variety of approaches that's outlined in the docs, without success.

`<quill v-model="article" :formats="editorFormats" output="html" :config="editorConfig" />`

```
      editorFormats: [
        {
          name: 'font',
        }
      ]
```

```
 editorConfig: {
        modules: {
          toolbar: [
            ['bold'],
            [
              { 'list': 'ordered' }, { 'list': 'bullet' }
            ]
          ]
        },
        theme: 'snow'
      }
```

Without any success. No matter the props sent to the component, the editor always looks like this:

![bilde](https://user-images.githubusercontent.com/706874/30543625-18c28acc-9c84-11e7-9842-18a9dd424eed.png)

**Comment by Sobient** [comment] 2017-09-18 13:39
Apparently it was somewhat convoluted, but this works:

```    
editorConfig: {
        modules: {
          toolbar: [
            [{ 'header': [1, 2, 3, 4, 5, 6, false] }, 'bold', 'italic', 'underline'],              // custom button values
            ['blockquote', { 'list': 'ordered' }, { 'list': 'bullet' }],
            ['link', { 'color': [] }, { 'align': [] }, 'clean']       // dropdown with defaults from theme
          ]
        },
        theme: 'snow',
        placeholder: 'Article text'
      },
```

The docs should be updated to better illustrate how this can be achieved.

**Comment by BrockReece** [comment] 2017-09-18 14:58
Hi @Sobient 

Thanks for your message

Maybe I have missed something but I'm not sure I see the changes between the config in your examples that caused the toolbar to update, it has been a while since I have messed around with the toolbar configs but I would have expected both of these configs to work.

**Comment by pdesmarais** [comment] 2018-03-19 18:11
The problem is because of line 82 in Quill.vue
```
this.editor = new Quill(this.$refs.quill, defaultsDeep(this.config, this.defaultConfig))
```

The defaultConfig contains a predefined toolbar as you can see
```
defaultConfig: {
    modules: {
        toolbar: [
            ['bold', 'italic', 'underline'],
            [{ 'list': 'ordered' }, { 'list': 'bullet' }],
            [{ 'align': [] }],
        ],
    },
    theme: 'snow',
}
```

Because `lodash.defaultsDeep` is being used, the config received in the props is merged with the defaultConfig.

The defaultConfig SHOULD be used only if the config received in props is not valid or empty. The problem with how it's done now is that I don't see how I can remove the `list` and `align` buttons. The only way I've managed to do it now is by passing this as my editor config :
```
{
    modules: {
        toolbar: [
            ['bold', 'italic', 'underline'],
            [false, false],
            [false]
        ]
    }
}
```

This creates another problem though. Quill adds buttons for undefined formats. Buttons are not visible and do nothing but cursor changes when passing over them.

Buttons should not be added to the default toolbar if a toolbar is passed in the config prop.

**Comment by BrockReece** [comment] 2018-04-02 07:53
Hey,  sorry for the delay with getting back to you on this.

Ok, I see what you are saying, removing the `defaultsDeep` merge though will introduce a massive breaking change. 

I may be able to check if a toolbar config is present and if so remove this from the default config?

**Comment by pdesmarais** [comment] 2018-04-03 13:49
@BrockReece I think that would be the way to go. If a toolbar config is passed, ignore the default config, if not, use the default config. Worst case scenario in this case is that there are toolbar actions that are not present anymore if they were not specified and used because they were present in the default config.

I don't see this as a breaking change as it doesn't stop the editor from working at all.

**Comment by BrockReece** [comment] 2018-04-03 13:56
@pdesmarais 

Ok lets do that. I will add some release notes too for anyone who is missing toolbar actions.

**Closed** 2018-04-12 07:34 UTC
